clc; clear; close all;

%% Make SEAL Videos
make_video('../../../data/cityscapes-preprocess/data_proc/leftImg8bit/demoVideo/stuttgart_00',...
    '../../../exper/cityscapes/result/test/demoVideo_stuttgart_00/seal/pred_color',...
    '../../../exper/cityscapes/result/video', 'demoVideo_stuttgart_00_seal', 17, 100);
make_video('../../../data/cityscapes-preprocess/data_proc/leftImg8bit/demoVideo/stuttgart_01',...
    '../../../exper/cityscapes/result/test/demoVideo_stuttgart_01/seal/pred_color',...
    '../../../exper/cityscapes/result/video', 'demoVideo_stuttgart_01_seal', 17, 100);
make_video('../../../data/cityscapes-preprocess/data_proc/leftImg8bit/demoVideo/stuttgart_02',...
    '../../../exper/cityscapes/result/test/demoVideo_stuttgart_02/seal/pred_color',...
    '../../../exper/cityscapes/result/video', 'demoVideo_stuttgart_02_seal', 17, 100);

%% Make SEAL Class-Wise Videos
make_clswise('../../../data/cityscapes-preprocess/data_proc/leftImg8bit/demoVideo/stuttgart_00',...
    '../../../exper/cityscapes/result/test/demoVideo_stuttgart_00/seal',...
    '../../../exper/cityscapes/result/video', 'demoVideo_stuttgart_00_seal_clswise', 17, 100);
make_clswise('../../../data/cityscapes-preprocess/data_proc/leftImg8bit/demoVideo/stuttgart_01',...
    '../../../exper/cityscapes/result/test/demoVideo_stuttgart_01/seal',...
    '../../../exper/cityscapes/result/video', 'demoVideo_stuttgart_01_seal_clswise', 17, 100);
make_clswise('../../../data/cityscapes-preprocess/data_proc/leftImg8bit/demoVideo/stuttgart_02',...
    '../../../exper/cityscapes/result/test/demoVideo_stuttgart_02/seal',...
    '../../../exper/cityscapes/result/video', 'demoVideo_stuttgart_02_seal_clswise', 17, 100);

%% Make CASENet-SEAL Comparison Videos
make_compare('../../../data/cityscapes-preprocess/data_proc/leftImg8bit/demoVideo/stuttgart_00',...
    '../../../exper/cityscapes/result/test/demoVideo_stuttgart_00/casenet/pred_color',...
    '../../../exper/cityscapes/result/test/demoVideo_stuttgart_00/seal/pred_color',...
    '../../../exper/cityscapes/result/video', 'demoVideo_stuttgart_00_compare', 17, 100);

make_compare('../../../data/cityscapes-preprocess/data_proc/leftImg8bit/demoVideo/stuttgart_01',...
    '../../../exper/cityscapes/result/test/demoVideo_stuttgart_01/casenet/pred_color',...
    '../../../exper/cityscapes/result/test/demoVideo_stuttgart_01/seal/pred_color',...
    '../../../exper/cityscapes/result/video', 'demoVideo_stuttgart_01_compare', 17, 100);

make_compare('../../../data/cityscapes-preprocess/data_proc/leftImg8bit/demoVideo/stuttgart_02',...
    '../../../exper/cityscapes/result/test/demoVideo_stuttgart_02/casenet/pred_color',...
    '../../../exper/cityscapes/result/test/demoVideo_stuttgart_02/seal/pred_color',...
    '../../../exper/cityscapes/result/video', 'demoVideo_stuttgart_02_compare', 17, 100);

%% Make Test Result Video
make_test('../../../data/cityscapes-preprocess/data_proc',...
    '../../../data/cityscapes-preprocess/data_proc/val.mat',...
    '../../../exper/cityscapes/result/vis/val',...
    '../../../exper/cityscapes/result/test/val/casenet/pred_color',...
    '../../../exper/cityscapes/result/test/val/seal/pred_color',...
    '../../../exper/cityscapes/result/video', 'val', 0.5, 100);